sources:
  - name: risk_analytics_mm
    schema: main
    tables:
      - name: township_summary_updated
      - name: infrastructure_township
      - name: earthquake_township
      - name: population
      - name: usgs_earthquakes